version: '3.8'
services:
  word-merger:
    container_name: word_merger
    restart: on-failure
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
    image: word-merger:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_HOST=mysql
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=wordmergerDB
      - DATABASE_PORT=3306
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordmergerDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306